### ISSUE TITLE
[PE-D] Module cannot be added when the order of prefixes are jumbled

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-4/tp#184]
![image.png](https://raw.githubusercontent.com/swongts/ped/main/files/1f74b2b8-1d1c-4016-9e54-d665d10e6f64.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: swongts/ped#3

**Comment by nvbinh15** [comment]
Mentioned in the UG that parameters cannot be reordered.

> Parameters cannot be reordered. Example: If the command specifies module add c/MODULE_CODE n/MODULE_NAME, keying in module add n/MODULE_NAME c/MODULE_CODE will result in an invalid command.
