### ISSUE TITLE
[PE-D] Add assignment for module that doesnt exist

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-4/tp#188]
![image.png](https://raw.githubusercontent.com/ShaoYurui/ped/main/files/6fe9364f-da34-4d7f-945e-809305ecffa0.png)

Add assignment for module that doesnt exist

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ShaoYurui/ped#5

**Comment by nvbinh15** [comment]
`task` is not relevant to `module`. Put a note in the UG for this issue.
