### ISSUE TITLE
[PE-D] Absence of line separatorafter food view

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-4/tp#192]
![image.png](https://raw.githubusercontent.com/ShaoYurui/ped/main/files/ad84bae3-f38a-4160-b42d-c2eca2859570.png)

After printing all the options, there is no line separator

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ShaoYurui/ped#7

**Comment by ngnigel99** [comment]
Lmao tester should've added negative calorie bug for this too.

**Comment by ngnigel99** [comment]
Closed with #234
