### ISSUE TITLE
[PE-D] Inconsistent input flags and params

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-4/tp#217]
Expected to be able to input with the presence of the ‘n/’ and ‘c/’ flag but required the presence of a space in front of input to be added. However, when adding in a similar format to modules it was allowed. Could make it consistent throughout the program.

![image.png](https://raw.githubusercontent.com/STAung07/ped/main/files/a6e85299-7392-4f03-b0bb-c126baa859f9.png)
 -No space needed

![image.png](https://raw.githubusercontent.com/STAung07/ped/main/files/29506d80-0459-4374-a497-5c9e19ae04b1.png)
-Space needed

Same problem for journal entries

![image.png](https://raw.githubusercontent.com/STAung07/ped/main/files/ec131a7f-bb03-48cc-b449-e22085dfa479.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: STAung07/ped#2

**Comment by ngnigel99** [comment]
Fixed with #229
