### ISSUE TITLE
[PE-D] Failure to type command; Only works if copy paste

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-4/tp#223]
When I typed out the command for calender display 10-2021 it failed to display. Only when I copy pasted the command from the User Guide then it worked.

![image.png](https://raw.githubusercontent.com/STAung07/ped/main/files/3af3b3bd-82b4-4588-9f49-bdd5a59cb873.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: STAung07/ped#8

**Comment by ngnigel99** [comment]
spelling error, oops
